### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by kompass** [kapil-varshney/utilities#1]
Hello,

Thank you very much for your share, is your code opensource ?
Could you add a license ?

https://opensource.org/licenses

Personally, I always use the MIT license for my personal projects to leave a total freedom of use.

**Comment by kapil-varshney** [comment]
Hi Nicolas,

You are welcome. Yes, the code is opensource.
I just added the MIT license. Thanks for the advice.

Cheers,


[image: --]

Kapil Varshney
[image: https://]about.me/kapilvarshney
<https://about.me/kapilvarshney?promo=email_sig>

**Comment by kompass** [comment]
Thank you !
